#!/usr/bin/env python3
"""Regenerate .claude-plugin/marketplace.json AND refresh muk SKILL.md inventory."""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MP = os.path.join(ROOT, ".claude-plugin", "marketplace.json")
MUK_SKILL = os.path.join(ROOT, "skills", "muk", "SKILL.md")
INV_START = "<!-- MUK_INVENTORY_START -->"
INV_END = "<!-- MUK_INVENTORY_END -->"


def frontmatter_desc(path):
    try:
        t = open(path).read(4000)
    except Exception:
        return ""
    mo = re.search(r"^description:\s*(.+)$", t, re.MULTILINE)
    return mo.group(1).strip().strip('"').strip("'") if mo else ""


def first_para(path, maxlen=180):
    try:
        t = open(path).read(4000)
    except Exception:
        return ""
    lines = [l.strip() for l in t.splitlines() if l.strip()]
    for i, l in enumerate(lines):
        if l.startswith("#") and i + 1 < len(lines):
            nxt = lines[i + 1]
            if not nxt.startswith("#") and not nxt.startswith("---"):
                return nxt[:maxlen]
    return ""


skills = []
for n in sorted(os.listdir(os.path.join(ROOT, "skills"))):
    sp = os.path.join(ROOT, "skills", n, "SKILL.md")
    if os.path.isfile(sp):
        skills.append({"name": n, "source": f"skills/{n}",
                       "description": frontmatter_desc(sp) or f"Skill: {n}",
                       "version": "1.0.0"})
skills.sort(key=lambda s: (not s["name"] == "muk", s["name"]))

plugins = []
for n in sorted(os.listdir(os.path.join(ROOT, "plugins"))):
    pj = os.path.join(ROOT, "plugins", n, ".claude-plugin", "plugin.json")
    desc = ""
    if os.path.isfile(pj):
        try:
            desc = json.load(open(pj)).get("description", "")
        except Exception:
            pass
    if not desc:
        desc = first_para(os.path.join(ROOT, "plugins", n, "README.md"))
    plugins.append({"name": n, "source": f"plugins/{n}",
                    "description": desc or f"Plugin: {n}", "version": "1.0.0"})

agents = []
for root, _, files in os.walk(os.path.join(ROOT, "agents")):
    for fn in sorted(files):
        if fn.endswith(".md"):
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, ROOT)
            cat = os.path.basename(os.path.dirname(full))
            agents.append({"name": fn[:-3], "category": cat, "source": rel,
                           "description": frontmatter_desc(full) or first_para(full) or f"Agent: {fn[:-3]}",
                           "version": "1.0.0"})

m = json.load(open(MP))
m["skills"] = skills
m["plugins"] = plugins
m["agents"] = [{k: v for k, v in a.items() if not k == "category"} for a in agents]
json.dump(m, open(MP, "w"), indent=2)

lines = [INV_START,
         "<!-- Auto-generated by scripts/sync_marketplace.py. Do not edit by hand. -->",
         "",
         "## Pack inventory (auto-generated)",
         "",
         f"**Summary:** {len(skills)} skills · {len(plugins)} plugins · {len(agents)} agents.",
         "",
         "### Skills", ""]
for s in skills:
    lines.append(f"- **{s['name']}** — {s['description']}")
lines += ["", "### Plugins", ""]
for p in plugins:
    lines.append(f"- **{p['name']}** — {p['description']}")
lines += ["", "### Agents (by category)", ""]
by_cat = {}
for a in agents:
    by_cat.setdefault(a["category"], []).append(a)
for cat in sorted(by_cat):
    lines += [f"#### {cat}", ""]
    for a in sorted(by_cat[cat], key=lambda x: x["name"]):
        lines.append(f"- **{a['name']}** — {a['description']}")
    lines.append("")
lines.append(INV_END)
block = "\n".join(lines)

muk = open(MUK_SKILL).read()
pat = re.compile(re.escape(INV_START) + r".*?" + re.escape(INV_END), re.DOTALL)
if pat.search(muk):
    muk = pat.sub(block, muk)
else:
    muk = muk.rstrip() + "\n\n" + block + "\n"
open(MUK_SKILL, "w").write(muk)

print(f"Synced: {len(skills)} skills, {len(plugins)} plugins, {len(agents)} agents")
